dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk8
install: ./mvnw -s "${TRAVIS_BUILD_DIR}/.travis/maven-settings.xml" -v
script: ./mvnw -s "${TRAVIS_BUILD_DIR}/.travis/maven-settings.xml" -B -nsu verify
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
  - "/^feature\\/.*$/"
env:
  global:
  - secure: X6sWPMVtn/FLKdNR8SKJF0A4JTIC5LUS1f+m2viTf5MiL3LiMKQxZ1jSIQvE3o+ZXD8qiArTJFYRAIzSO4BvUZxNSvUgEShFY01M1W4pRpE2h5C8nDfdz4gezRAfqj2qZWMZ4S2SwRqp9UA6TEEaAPX6kuvtAaw5IdSiT4humrYTJhn50JFyW487KlS+F9zxe75YpzjVyRoLfjGPlPSqtxVU+tq3qwEekxFB1q6mYJ/RPpvxhftURMIcvtw8ao2kxBTPqZdupNAXoHCB9zjXzoBcc3wOrjeGIO2Kf2sbnqdsRQqf0oh7EjbTexMT9izIf6Wtvr3udUgUQRbC4YlYqlS2/43O4M0K0ZPw05HexJ73ApORc3YeN/wrZfnL7LhhIok5iIJuVsH9WVpjHzsHRCty5RGpc7I3qrca7nV+VIvE6OfXjjSNeS19YpDYcYo/q9ocUbdTsROcyRWLFXg6qLIdwJYybC637HhW5dQwMETvJMXN7tSKp83qetjLs4m1o3Al7rx4ovM0pJRicUrrVZYn7/igwgabZpxWOmjH/v6k0KCXh2T0d1eyFUdiNqVEbNlhhA+NU6zVMsxLRLHasUrAeJtZZ9q8o9/ALbGLVw7tPMSUDnGWpnz981LDbj/0QuHdEnYlR5J7XpV282ZtVI+CEqTCRwfVk4nHpv1oiYY=
  - secure: DWAqq/bb18SdTD9obU3vqKLBwZgH6AbcNS9Xu1rB7FkrEr6xC+W//IWfhieL9t0obXa3GiCvt4yvPg+2USVNXBx6m1wr6hTn9nYRvVHkw+oS4QHz6eWBOwh8KOPOrzX0Q3CvwAxghD9hcYcnrZUdNFTDeQv6y+iZyYfEZXmtgT+ZQ4B54lrPkWci00JMF6LaSHVxOKLKfPb67yClV29gTe46ITY2jkJt69493FBQAEKe+DhnTM6BT4xprEJOxm1b9YqJTS94x+zSEgf2Cv73Cv4Wwd01sOUgOSoy/eW1IrMbsMR+1Sb3yjZQC3wjdrxvzyM6djh34NitsIKd0sXr0aba88BZNkOZx4AHzT8RbED1zlOYIcC9asFE2BGZhE50SYUAqbLVCVUumeJQeAORj+HeztGa250NpZHwL4FFo/bc2Tnq8I9AsaIkfjCj+4Xyp4lg7VOFXN/9cbstMuRGfq3saGZ1RfLrw6VfQ83Ymu5LsCy3akRqNfh3dLqkrWKYqD2IVuYNlxuCddO3P7slrpN3yLPYnVubMyf0BLCrVBiC+FXG0zmuYZyqZOYFIOq+KybuaYKakbksk4usjLkBC1TZMXdXJjny8Dnv3wihEFq6nUN3H2MANwvJ7OAkPpKdSGW1uKtIkQifMB5WzKlgNRQ3WGaHD886dqjjjxEwCWE=
